#!/usr/bin/fish
# sets up the environment variables in the current session
# works only in fish shell
# works only by running using '. ./<script name>'
set HBNB_ENV test 
set HBNB_MYSQL_USER hbnb_test 
set HBNB_MYSQL_PWD hbnb_test_pwd 
set HBNB_MYSQL_HOST localhost 
set HBNB_MYSQL_DB hbnb_test_db 
set HBNB_TYPE_STORAGE db
